In [1]:
import tensorflow as tf

In [6]:
t = tf.constant([
                 [1.,2.,3.],
                 [4.,5.,6.]
                 ])
print('---------------')

print(t.shape)  # (2, 3)
print('---------------')

print(t.dtype)  # <dtype: 'float32'>
print('---------------')

print(t[:, 1:],' ')  
# tf.Tensor(
# [[2. 3.]
#  [5. 6.]], shape=(2, 2), dtype=float32)  
print('---------------')

print(t[:, 1:, tf.newaxis])
# tf.Tensor(
# [[[2.]
#   [3.]]
#  [[5.]
#   [6.]]], shape=(2, 2, 1), dtype=float32)
print('---------------')

print(t+10) 
# tf.Tensor(
# [[11. 12. 13.]
#  [14. 15. 16.]], shape=(2, 3), dtype=float32)
print('---------------')

print(tf.add(t,10))
# tf.Tensor(
# [[11. 12. 13.]
#  [14. 15. 16.]], shape=(2, 3), dtype=float32)
print('---------------')

print(t @ tf.transpose(t))
# tf.Tensor(
# [[14. 32.]
#  [32. 77.]], shape=(2, 2), dtype=float32)
print('---------------')

print(tf.matmul(t,tf.transpose(t)))
# tf.Tensor(
# [[14. 32.]
#  [32. 77.]], shape=(2, 2), dtype=float32)
print('---------------')

print(tf.square(t))
print('---------------')
# tf.Tensor(
# [[ 1.  4.  9.]
#  [16. 25. 36.]], shape=(2, 3), dtype=float32)

print(tf.constant(42) ) 
# tf.Tensor(42, shape=(), dtype=int32)
print('---------------')


---------------
(2, 3)
---------------
<dtype: 'float32'>
---------------
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)  
---------------
tf.Tensor(
[[[2.]
  [3.]]

 [[5.]
  [6.]]], shape=(2, 2, 1), dtype=float32)
---------------
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
---------------
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
---------------
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)
---------------
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)
---------------
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
---------------
tf.Tensor(42, shape=(), dtype=int32)
---------------


In [ ]:
# import keras.backend as K
# K.square() , K.exp() , K.sqrt()

In [ ]:
# tf.add(), ---eynile   tf.math.add()
# tf.multiply(),
# tf.square(),
# tf.exp(),
# tf.sqrt(),
# tf.reshape(),
# tf.squeeze(),
# tf.tile(),
# tf.reduce_mean(),
# tf.reduce_sum(),
# tf.reduce_max(),
# tf.math.log() 

Tensors and NumPy


In [ ]:
import numpy as np 

a  = np.array([2. , 4. , 5.])
print(tf.constant(a)) 
# tf.Tensor([2. 4. 5.], shape=(3,), dtype=float64)
print('--------')


t = tf.constant([
                 [1.,2.,3.],
                 [4.,5.,6.]
                 ])
print(t.numpy())      # np.array(t)
# [[1. 2. 3.]
#  [4. 5. 6.]]
print('--------')

print(tf.square(a))  # print(np.square(t))
# tf.Tensor([ 4. 16. 25.], shape=(3,), dtype=float64)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float64)
--------
[[1. 2. 3.]
 [4. 5. 6.]]
--------
tf.Tensor([ 4. 16. 25.], shape=(3,), dtype=float64)


Type Conversions


In [ ]:
# Error  verecek

 
# tf.constant(2.) + tf.constant(40)
# tf.constant(2.) + tf.constant(40., dtype=tf.float64)

In [12]:
t2 = tf.constant(40., dtype=tf.float64)

print(t2.dtype)  
# tf.Tensor(40.0, shape=(), dtype=float64)

print(tf.constant(2.0) + tf.cast(t2, tf.float32)) # cast -la tip  cevirmesi  
# tf.Tensor(42.0, shape=(), dtype=float32)

<dtype: 'float64'>
tf.Tensor(42.0, shape=(), dtype=float32)


Variables


In [ ]:
t = tf.constant([[1., 2., 3.],
                 [4., 5., 7.]])

# Tensorlar immutabledir   
# t-ni dəyişdirmək MÜMKÜN DEYİL

In [22]:
v = tf.Variable([[1., 2., 3.],
                 [4., 5., 6.]])

# Nəticə: shape=(2, 3), dtype=float32 
# Dəyər: [[1., 2., 3.], 
#         [4., 5., 6.]]
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>


In [ ]:
print(v)   
# array([[1., 2., 3.],
#        [4., 5., 6.]], dtype=float32)>
print('1------------------------------------------')


print(v.assign(2 * v))   
# v now equals [[2., 4., 6.],
#               [8., 10., 12.]]
print('2------------------------------------------')


print(v[0, 1].assign(42) )      
# v now equals [[2., 42., 6.],
#              [8., 10., 12.]]
print('3------------------------------------------')

# sutun  deyisme
print(v[:, 2].assign([0., 1.])) 
# v now equals [[2., 42., 0.], 
#               [8., 10., 1.]]
print('4------------------------------------------')


# birden cox index-e gore deyisme
print(v.scatter_nd_update(
    indices=[[0, 0],[1, 2]],  # dəyişəcək indekslər
    updates=[100., 200.]        # yeni dəyərlər
)
)
# v = [[100., 42., 0.],
#     [8., 10., 200.]]
# (0,0) -> 100, (1,2) -> 200
print('5------------------------------------------')


# toplama
print(v.assign_add([[1., 1., 1.],
                    [1., 1., 1.]  ]) ) 
# array([[101.,  43.,   1.],
#        [ 17.,  21., 201.]],
print('6------------------------------------------')


# cixma 
print(v.assign_sub([[1., 1., 1.], 
                    [1., 1., 1.]  ])  )
# array([[100.,  42.,   0.],
#        [ 16.,  20., 200.]],
print('7------------------------------------------')




<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10.,   1.]], dtype=float32)>
1------------------------------------------
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[200.,  84.,   0.],
       [ 16.,  20.,   2.]], dtype=float32)>
2------------------------------------------
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[200.,  42.,   0.],
       [ 16.,  20.,   2.]], dtype=float32)>
3------------------------------------------
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[200.,  42.,   0.],
       [ 16.,  20.,   1.]], dtype=float32)>
4------------------------------------------
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [ 16.,  20., 200.]], dtype=float32)>
5------------------------------------------
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[101.,  43.,   1.],
       [ 17.

In [ ]:
# v[1] = [7., 8., 9.] # 'ResourceVariable' object does not support item assignment


#### Other Data Structures


- Sparse tensors (tf.SparseTensor)

Normal tensor: [1, 0, 0, 0, 5, 0, 0, 0, 0, 2]

Seyrək tensor: yalnız sıfır olmayanları saxla

Dəyərlər: [1, 5, 2]

İndekslər: [0, 4, 9]

- Tensor arrays (tf.TensorArray)

Butun  tensorlar eyni  olcude olamlidir, sabit uzunluq ,  Genislene bilen 

- Ragged tensors (tf.RaggedTensor)

Normal tensor: hər sətir bərabər ölçüdə
[[1, 2, 3], [4, 5, 6]]  # 2×3

Ragged tensor: sətirlər müxtəlif ölçülü
[[1, 2], [3, 4, 5, 6], [7]]  # müxtəlif uzunluqlar

- String tensors

Byte string (UTF-8) : - tf.constant("café")  # b"caf\xc3\xa9"

Unicode tensor (rəqəmlərlə) : - tf.constant([99, 97, 102, 233])  # café

- Sets

 İki set: {1, 2} və {3, 4}

tf.constant([[1, 2], [3, 4]])

Birlesme ,  Kesisme , ferq emeliyyatlari isleyir.

- Queues

FIFOQueue - İlk girən, ilk çıxar

PriorityQueue - Öncəlikli elementlər

RandomShuffleQueue - Qarışdırılmış növbə

PaddingFIFOQueue - Müxtəlif ölçülü məlumatlar

#### HUBER LOSS FUNKSİYASININ IMPLEMENTASİYASI:

In [ ]:
def huber_fn(y_true, y_pred):
 error = y_true - y_pred
 print(error)
 
 is_small_error = tf.abs(error) < 1       # Thredhold =1
 print(is_small_error)
 
 squared_loss   = tf.square(error) / 2   # Kicik sehvler ucun 
 print(squared_loss)

 linear_loss    = tf.abs(error) - 0.5    # Boyuk sehvler ucun
 print(linear_loss)
  
 return  tf.where(is_small_error, squared_loss, linear_loss)
# where(yoxlama,odenerse,ondenmezse)

#          # Modeli compile edərkən xüsusi loss-u göstərin
# model.compile(loss=huber_fn, optimizer="nadam")
#          # Normal şəkildə train edin
# model.fit(X_train, y_train, ...)


huber_fn(0.2,0.6)

-0.39999999999999997
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(0.080000006, shape=(), dtype=float32)
tf.Tensor(-0.099999994, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.080000006>

##### CUSTOM LOSS SAXLANILMASI

In [ ]:
# Yükləyərkən custom_objects dictionary-si təqdim etməlisiniz

model = tf.keras.models.load_model("my_model_with_a_custom_loss",
                                    custom_objects={"huber_fn": huber_fn})



In [ ]:
# PROBLEM  : Threshold kimi parametrlər yadda saxlanılmır

def create_huber(threshold = 1.0):
    
    def huber_fn(y_true,y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold 
        squared_loss   = tf.abs(error) / 2
        linear_loss    = threshold * tf.abs(error) - threshold **2 / 2 
    
        return tf.where(is_small_error ,squared_loss , linear_loss)
    
    return  huber_fn

model.compile(loss = create_huber(2.0), optimizer = 'nadam')


NameError: name 'model' is not defined

In [ ]:
# parametr yene gosterilir
model = tf.keras.models.load_model("my_model_with_a_custom_loss_threshold_2",
                                     custom_objects = {"huber_fn": create_huber(2.0)})




In [ ]:
# HƏLL YOLU: Loss SUBCLASS-ı YARATMAQ

class HuberLoss(tf.keras.losses.Loss):
 
 def __init__(self, threshold=1.0, **kwargs):
    self.threshold = threshold
    super().__init__(**kwargs)
 
 def call(self, y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < self.threshold
    squared_loss = tf.square(error) / 2
    linear_loss = self.threshold * tf.abs(error) - self.threshold**2 / 2

    return tf.where(is_small_error, squared_loss, linear_loss)
 
 def get_config(self):
    base_config = super().get_config()
    print("base_config:", base_config)  # GÖRÜN NƏ QAYIDIR?
    return {**base_config, "threshold": self.threshold}
 
#  base config-in yoxlamasi 

loss = HuberLoss(  threshold=2.0, 
                 # reduction='sum',
                   name='my_huber'
                   )
config = loss.get_config()
print("Yekun config:", config)

base_config: {'reduction': 'auto', 'name': 'my_huber'}
Yekun config: {'reduction': 'auto', 'name': 'my_huber', 'threshold': 2.0}


In [ ]:
model.compile(loss=HuberLoss(2.), optimizer="nadam")

# Yükləyərkən sadəcə class-ı göstərin
model = tf.keras.models.load_model("my_model_with_a_custom_loss_class",
                                   custom_objects={"HuberLoss": HuberLoss})

----------------


#### FUNKSIYA 


In [ ]:
# Xüsusi aktivasiya funksiyası (softplus-a bənzər)
def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))

# Xüsusi Glorot inisializatoru
def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)

# Xüsusi L1 requlyarizatoru
def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))

# Xüsusi konstraint (bütün çəkilər müsbət olmalı)
def my_positive_weights(weights):
    return tf.where(weights < 0., tf.zeros_like(weights), weights)

layer = tf.keras.layers.Dense(
                        1,
                        activation        = my_softplus,           # Aktivasiya
                        kernel_initializer= my_glorot_initializer, # İnisializator
                        kernel_regularizer= my_l1_regularizer,     # Requlyarizator
                        kernel_constraint = my_positive_weights    # Konstraint
                    )


#### CLASS


In [ ]:
# Class versiyası ilə parametrli regularizer yarada bilirik!

class MyL1Regularizer(tf.keras.regularizers.Regularizer):

    def __init__(self, factor):
        self.factor = factor #  yuxaridaki  0.1 dir.
    
    def __call__(self, weights):
        return tf.reduce_sum(tf.abs(self.factor * weights))
    
    def get_config(self):

        return {"factor": self.factor}
    

# Əvvəl (funksiya ilə):
regularizer = my_l1_regularizer   # factor dəyişə bilmərik

# İndi (class ilə):
regularizer = MyL1Regularizer(factor=0.05)  # factor-ü təyin edirik
print(regularizer.get_config())

layer = tf.keras.layers.Dense(
                    10,
                    kernel_regularizer=regularizer  # factor=0.05 ilə işləyəcək
                )
layer.get_weights()



{'factor': 0.05}


<bound method Layer.get_weights of <keras.src.layers.core.dense.Dense object at 0x0000024F0455B850>>

### Custom Metrics 

In [ ]:
model.compile(loss="mse", optimizer="nadam", metrics=[create_huber(2.0)])

Streaming Metric — tf.keras.metrics.Precision

In [50]:
precision = tf.keras.metrics.Precision()

precision([0, 1, 1, 1, 0, 1, 0, 1],
          [1, 1, 0, 1, 0, 1, 0, 1])


<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [ ]:
# Umumi  precision 
precision([0, 1, 0, 0, 1, 0, 1, 1],
          [1, 0, 1, 1, 0, 0, 0, 0])


<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [52]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [53]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>]

In [54]:
precision.reset_states()

Custom Streaming Metric yaratmaq

In [ ]:
class HuberMetric(tf.keras.metrics.Metric):
    def __init__(self, threshold=1.0, **kwargs):
        super().__init__(**kwargs)  # Ana klasın parametrlərini işlə
        self.threshold = threshold   # Threshold dəyərini saxla
        self.huber_fn = create_huber(threshold)  # Huber funksiyasını yarat
        self.total = self.add_weight("total", initializer="zeros") # BÜTÜN itkilərin cəmi (əvvəl 0)
        self.count = self.add_weight("count", initializer="zeros") # NÜMUNƏLƏRİN sayı (əvvəl 0)

    def update_state(self, y_true, y_pred, sample_weight=None):
        sample_metrics = self.huber_fn(y_true, y_pred)  # Hər nümunə üçün itki
        
        # Batch-dəki itkiləri cəmlə və ümumi cəmə əlavə et
        self.total.assign_add(tf.reduce_sum(sample_metrics))
        # Batch-dəki nümunə sayını götür və ümumi sayı artır
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))
    
    def result(self):
        return self.total / self.count  # ORTALAMA itki = cəm / say
    
    def get_config(self):
        base_config = super().get_config()  # Ana klasın konfiqini al
        return {**base_config, "threshold": self.threshold}  # Öz parameteri də əlavə et

### Custom Layers

#### Weight-i olmayan custom layer


In [ ]:

# Lambda ilə sadə üsul
exponential_layer = tf.keras.layers.Lambda(lambda x: tf.exp(x))

# İstifadəsi:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    exponential_layer,  # Hər dəyəri exp()-dən keçir
    tf.keras.layers.Dense(1)
])

#### Stateful (weight-li) Custom Layer yaratmaq

In [ ]:
class MyDense(tf.keras.layers.Layer):
    # 1️⃣ CONSTRUCTOR (__init__) - Layer-i yaradırıq
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)        # Ana klasın parametrlərini ötür
        self.units = units                 # Neçə neyron? (10, 20, 100...)
        # Activation-ı qəbul et (string, funksiya və ya None)
        self.activation = tf.keras.activations.get(activation)

    # 2️⃣ build() - Çəkiləri yaradır (input ölçüsü bəlli olandan sonra)
    def build(self, batch_input_shape):
        # KERNEL - girişlərlə neyronlar arasındakı çəkilər
        # Şəkil: [giriş_sayı, neyron_sayı]
        self.kernel = self.add_weight(
                name="kernel",
                shape=[batch_input_shape[-1], self.units],
                initializer="glorot_normal")   # İlkin dəyər metodu

        # BIAS - hər neyronun qərəzi
        # Şəkil: [neyron_sayı]
        self.bias = self.add_weight(
                        name="bias",
                        shape=[self.units],
                        initializer="zeros")  # Qərəzlər 0-dan başlayır

    # 3️⃣ call() - İrəli hesablama (forward pass)
    def call(self, X):
        # X @ kernel + bias  =  giriş * çəkilər + qərəz
        # Sonra activation-dan keçir (ReLU, sigmoid və s.)
        return self.activation(X @ self.kernel + self.bias)
    
    # Lakin dynamic layer varsa (məsələn, ölçü dəyişir)
    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.units)  # batch_size, units

    # 4️⃣ get_config() - Yaddaş üçün parametrləri saxla
    def get_config(self):
        base_config = super().get_config()      # Ana klasın konfiqi
        return {
            **base_config,                       # Hamısını birləşdir
            "units": self.units,                  # Öz parametrimiz
            "activation": tf.keras.activations.serialize(self.activation)  # Activation adı
        }



In [ ]:
# Çox Girişli / Çox Çıxışlı Layer

class MyMultiLayer(tf.keras.layers.Layer):
    def call(self, X):
        X1, X2 = X                    # 2 giriş gəlir
        çıxış1 = X1 + X2               # Toplama
        çıxış2 = X1 * X2               # Vurma  
        çıxış3 = X1 / X2               # Bölmə
        return çıxış1, çıxış2, çıxış3  # 3 çıxış qaytarır

In [ ]:
# Training/Testing Fərqli Davranış

class MyGaussianNoise(tf.keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super().__init__(**kwargs)
        self.stddev = stddev
    
    def call(self, X, training=False):
        if training:
            # TRAINING: səs əlavə et
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        else:
            # TESTING: təmiz X
            return X

### Custom Models 

In [ ]:
# Subclassing API  yanasmasi

class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        # Layer-ləri burada yarat
        self.dense1 = tf.keras.layers.Dense(10)
    
    def call(self, inputs):
        # Forward pass məntiqi
        return self.dense1(inputs)

In [57]:
#  Residual  bloku
class ResidualBlock(tf.keras.layers.Layer):
    def __init__(self, n_layers, n_neurons):
        super().__init__()
        # İçində bir neçə Dense layer saxlayır
        self.hidden = [tf.keras.layers.Dense(n_neurons, activation="relu") 
                       for _ in range(n_layers)]
    
    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:  # Bütün layer-lərdən keç
            Z = layer(Z)
        return inputs + Z  # Skip connection (girişi əlavə et)

In [58]:
# Tam sekilde 

class ResidualRegressor(tf.keras.Model):
    def __init__(self, output_dim):
        super().__init__()
        self.hidden1 = tf.keras.layers.Dense(30, activation="relu")
        self.block1 = ResidualBlock(2, 30)  # 2 layer-li blok
        self.block2 = ResidualBlock(2, 30)  # 2 layer-li blok
        self.out = tf.keras.layers.Dense(output_dim)
    
    def call(self, inputs):
        Z = self.hidden1(inputs)
        # Eyni bloku 4 dəfə təkrarla
        for _ in range(4):
            Z = self.block1(Z)
        Z = self.block2(Z)  # Başqa blok
        return self.out(Z)

In [59]:
# ISTIFADESI

# model.compile(...)
# model.fit(...)
# model.evaluate(...)
# model.predict(...)


In [ ]:
# SAVE ETMEK

# model.save()
# tf.keras.models.load_model()

# ve ya 

# model.save_weights()
# model.load_weights()


### Model Daxili Loss və Metric

In [61]:
class ReconstructingRegressor(tf.keras.Model):
    # ========== 1. CONSTRUCTOR ==========
    def __init__(self, output_dim):
        super().__init__()
        # 5 gizli təbəqə - hər biri 30 neyronlu
        self.hidden = [tf.keras.layers.Dense(30, activation="relu") 
                       for _ in range(5)]
        # Əsas çıxış təbəqəsi (regresiya üçün)
        self.out = tf.keras.layers.Dense(output_dim)
        # Reconstruction error-u izləmək üçün METRIC
        # Mean() = bütün batch-lərin ortalamasını saxlayır
        self.reconstruction_mean = tf.keras.metrics.Mean(name="reconstruction_error")
    
    # ========== 2. BUILD ==========
    def build(self, batch_input_shape):
        # batch_input_shape = (batch_size, input_feature_sayı)
        # Məsələn: (None, 64) -> 64 feature
        n_inputs = batch_input_shape[-1]  # input_feature_sayı = 64
        # Reconstruction layer - input-u bərpa etmək üçün
        # Çıxış ölçüsü input-la EYNİ olmalıdır!
        self.reconstruct = tf.keras.layers.Dense(n_inputs)
    
    # ========== 3. CALL (FORWARD PASS) ==========
    def call(self, inputs, training=False):
        # inputs = giriş məlumatları
        # ----- Gizli təbəqələrdən keçid -----
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)  # Z = gizli reprezentasiya
        # ----- INPUT-U BƏRPA ET -----
        reconstruction = self.reconstruct(Z)  # Gizli reprezentasiyadan input-u bərpa et
        # ----- RECONSTRUCTION LOSS -----
        # MSE: (reconstruction - inputs)^2 ortalaması
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        # ----- LOSS-U MODELƏ ƏLAVƏ ET -----
        # 0.05 = çəki faktoru (əsas loss-u basmasın deyə)
        self.add_loss(0.05 * recon_loss)  # Bu loss avtomatik ümumi loss-a əlavə olunur
        # ----- TRAINING ZAMANI METRIC-I YENİLƏ -----
        if training:
            # reconstruction_error metric-inə dəyər əlavə et
            self.add_metric(recon_loss, name="reconstruction_error")
        # ----- ƏSAS ÇIXIŞ (REGRESİYA) -----
        return self.out(Z)

### Autodiff 

In [ ]:
# 1. Sadə funksiya nümunəsi:


def f(w1, w2):
    return 3 * w1 ** 2 + 2 * w1 * w2

# (w1, w2) = (5, 3) üçün:
# Əl ilə: ∂f/∂w1 = 36, ∂f/∂w2 = 10

In [ ]:
# Gradient Tape - Əsas istifadə:

w1 = tf.Variable(5.0)
w2 = tf.Variable(3.0)

with tf.GradientTape() as tape:
    z = f(w1, w2)

gradients = tape.gradient(z, [w1, w2])
print(gradients)  # [36.0, 10.0]

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>, <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]


In [ ]:
# Təkrar gradient üçün:

with tf.GradientTape(persistent=True) as tape:
    z = f(w1, w2)
grad1 = tape.gradient(z, w1)
# gradient() çağırıldıqdan sonra tape silinir.
grad2 = tape.gradient(z, w2)

del tape  # Təmizləmək vacib!  yoxsa eror edecek
print(grad1,'\n',grad2 )

tf.Tensor(36.0, shape=(), dtype=float32) 
 tf.Tensor(10.0, shape=(), dtype=float32)


In [ ]:
# yalnız Variable izlənir

c1, c2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape() as tape:
    z = f(c1, c2)
gradients = tape.gradient(z, [c1, c2])
gradients
# [None, None]
# Çünki constant obyektlər izlənmir.



[None, None]

In [86]:
# Constant izləmək üçün:

c1 = tf.constant(5.0)
with tf.GradientTape() as tape:
    tape.watch(c1)  # Constant-ı izlə
    z = f(c1, w2)
gradients = tape.gradient(z, [c1, c2])
gradients
# Nəticə:
# [36., 10.]


[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>, None]

In [ ]:
#  Gradient-i dayandırmaq:

def f(w1, w2):
    return 3 * w1 ** 2 + tf.stop_gradient(2 * w1 * w2)

with tf.GradientTape() as tape:
    z = f(w1, w2)

gradients = tape.gradient(z, [w1, w2])
gradients
# nəticə: [tensor 30., None]



[<tf.Tensor: shape=(), dtype=float32, numpy=30.0>, None]

In [ ]:
x = tf.Variable(1e-50)
with tf.GradientTape() as tape:
    z = tf.sqrt(x)  # Çox kiçik ədədin kvadrat kökü
tape.gradient(z, x)  # [inf] - sonsuz!

# Həlli: kiçik epsilon əlavə et
z = tf.sqrt(x + 1e-6)

In [89]:
def my_softplus(z):
    return tf.math.log(1 + tf.exp(-tf.abs(z))) + tf.maximum(0., z)

with tf.GradientTape() as tape:
    k = my_softplus(z)

gradients = tape.gradient(k, [z])
gradients

[None]

In [ ]:
#  Custom gradient yarat

@tf.custom_gradient
def my_softplus(z):
    # Əsas funksiya (forward pass)
    result = tf.math.log(1 + tf.exp(-tf.abs(z))) + tf.maximum(0., z)
    
    # Xüsusi gradient funksiyası (backward pass)
    def my_softplus_gradients(grads):
        # grads = yuxarıdan gələn gradient
        return grads * (1 - 1/(1 + tf.exp(z)))  # Stabil gradient
        
    return result, my_softplus_gradients

### Custom Training Loops

In [ ]:
# ========== 1. MODEL (L2 regularizer ilə) ==========
l2_reg = tf.keras.regularizers.l2(0.05)  # 0.05 = regularization gücü

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(30, activation="relu", 
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2_reg),  # L2 regularization
    tf.keras.layers.Dense(1, kernel_regularizer=l2_reg)
])

In [ ]:
# ========== 2. KÖMƏKÇİ FUNKSİYALAR ==========
def random_batch(X, y, batch_size=32):
    """Dataset-dən təsadüfi batch seçir"""
    idx = np.random.randint(len(X), size=batch_size)
    return X[idx], y[idx]

def print_status_bar(step, total, loss, metrics=None):
    """Təlim statusunu göstərir (eyni sətirdə yenilənir)"""
    metrics_str = " - ".join([f"{m.name}: {m.result():.4f}" 
                              for m in [loss] + (metrics or [])])
    end = "" if step < total else "\n"
    print(f"\r{step}/{total} - {metrics_str}", end=end)

In [ ]:
# ========== 3. HYPERPARAMETRLƏR ==========
n_epochs = 5
batch_size = 32
n_steps = len(X_train) // batch_size  # Hər epoch-da neçə batch

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
loss_fn = tf.keras.losses.mean_squared_error

# Metric-lər (streaming - yığılır)
mean_loss = tf.keras.metrics.Mean(name="mean_loss")
metrics = [tf.keras.metrics.MeanAbsoluteError()]

In [ ]:
# ========== 4. ƏSAS TRAIN LOOP ==========
for epoch in range(1, n_epochs + 1):
    print(f"Epoch {epoch}/{n_epochs}")
    
    for step in range(1, n_steps + 1):
        # Batch seç
        X_batch, y_batch = random_batch(X_train_scaled, y_train)
        
        # Gradient hesabla
        with tf.GradientTape() as tape:
            y_pred = model(X_batch, training=True)  # Forward pass
            main_loss = tf.reduce_mean(loss_fn(y_batch, y_pred))  # MSE
            # ƏSAS: main_loss + bütün regularization loss-ları
            loss = tf.add_n([main_loss] + model.losses) # model.losses = L2 loss
        
        # Gradient-ləri hesabla və tətbiq et
        gradients = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
        
        # Metric-ləri yenilə
        mean_loss(loss)  # Loss-u yığ
        for metric in metrics:
            metric(y_batch, y_pred)  # MAE-ni yığ
        
        # Status göstər
        print_status_bar(step, n_steps, mean_loss, metrics)
    
    # Hər epoch sonu metric-ləri SIFIRLA (yeni epoch üçün)
    for metric in [mean_loss] + metrics:
        metric.reset_states()

### TensorFlow Functions və Graphs

In [91]:
# Adi Python funksiyası
def cube(x):
    return x ** 3

# TF function-a çevir
@tf.function
def tf_cube(x):
    return x ** 3

# İstifadəsi eynidir:
print(cube(2))       # 8 (Python int)
print(tf_cube(2))    # 8 (Tensor)

8
tf.Tensor(8, shape=(), dtype=int32)


In [98]:
tf_cube = tf.function(cube)
print(tf_cube(2))  # <tf.Tensor: shape=(), dtype=int32, numpy=8>
print(tf_cube(tf.constant(2.0)))  # <tf.Tensor: shape=(), dtype=float32, numpy=8.0>



tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(8.0, shape=(), dtype=float32)


In [99]:
# XLA ilə daha da sürətli

@tf.function(jit_compile=True)  # XLA aktiv!
def fast_function(x):
    return x ** 3



In [102]:
# Polymorphism (Çoxşəkilli)

print(tf_cube(10))       # int scalar → graph 1
print(tf_cube(20)    )    # eyni graph (cache)
print(tf_cube(tf.constant([10, 20])))    # list → graph 2
print(tf_cube(10.0))                      # float → graph 3

tf.Tensor(1000, shape=(), dtype=int32)
tf.Tensor(8000, shape=(), dtype=int32)
tf.Tensor([1000 8000], shape=(2,), dtype=int32)
tf.Tensor(1000, shape=(), dtype=int32)


### AutoGraph və Tracing 

In [115]:
#  Sizin yazdığınız:

import tensorflow as tf

# Adi Python funksiyası
@tf.function
def sum_squares(x):
    total = 0
    for i in range(x):  # Python for loop
        total += i ** 2
    return total

# Tracing merheelsi 
result = sum_squares(tf.constant(10))
print(result)  # 30 (0²+1²+2²+3²+4²)

# AutoGraph-un yaratdığı koda baxaq
print(tf.autograph.to_code(sum_squares.python_function))

tf.Tensor(285, shape=(), dtype=int32)
def tf__sum_squares(x):
    with ag__.FunctionScope('sum_squares', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        total = 0

        def get_state():
            return (total,)

        def set_state(vars_):
            nonlocal total
            (total,) = vars_

        def loop_body(itr):
            nonlocal total
            i = itr
            total = ag__.ld(total)
            total += i ** 2
        i = ag__.Undefined('i')
        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(x),), None, fscope), None, loop_body, get_state, set_state, ('total',), {'iterate_names': 'i'})
        try:
            do_return = True
            retval_ = ag__.ld(total)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [113]:
# AutoGraph çevirir:

def tf_sum_squares(x):
    total = 0
    
    # loop_body = hər addımda nə olacaq
    def loop_body(i):
        nonlocal total
        total += i ** 2
    
    # for loop-u TF while_loop-a çevir
    tf.for_stmt(
        loop_vars=[total],
        loop_body=loop_body,
        loop_range=range(x)
    )
    
    return total

In [116]:
# Yaradılan Qrafikə Necə Baxmaq Olar?

import tensorflow as tf
import datetime

# Funksiya
@tf.function
def sum_squares(x):
    total = 0
    for i in range(x):
        total += i ** 2
    return total

# TensorBoard üçün log qovluğu
log_dir = "logs/func/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# Trace aktiv et
tf.summary.trace_on(graph=True, profiler=True)

# Funksiyanı çağır
result = sum_squares(tf.constant(5))
print(f"Nəticə: {result}")

# Trace-i yaz
with tf.summary.create_file_writer(log_dir).as_default():
    tf.summary.trace_export(
        name="sum_squares",
        step=0,
        profiler_outdir=log_dir
    )

print(f"\nTensorBoard-u işə sal:")
print(f"tensorboard --logdir {log_dir}")
print(f"\nSonra brauzerdə http://localhost:6006 açın")

Instructions for updating:
use `tf.profiler.experimental.start` instead.
Nəticə: 30
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.

TensorBoard-u işə sal:
tensorboard --logdir logs/func/20260305-000553

Sonra brauzerdə http://localhost:6006 açın


### TF Function Qaydaları 

In [ ]:
# 1️⃣ Yalnız TensorFlow əməliyyatları qrafikə düşür

@tf.function
def f(x):
    # return np.sum(x)  # ❌ NumPy - yalnız tracing-də işləyir
    return tf.reduce_sum(x)  # ✅ TF ops - qrafikə düşür

In [ ]:

# 2️⃣ Side effects (print, counter) yalnız tracing-də işləyir

@tf.function
def f(x):
    print("Tracing!")  # ❌ Hər çağırışda YOX, yalnız 1 dəfə
    tf.print("Hər dəfə")  # ✅ TF print - hər çağırışda işləyir

In [ ]:
# 3️⃣ Variable-lar xaricdə yaradılmalıdır

v = tf.Variable(0)  # ✅ Xaricdə yarat

@tf.function
def f(x):
    v.assign_add(x)  # ✅ assign() istifadə et
    # v = v + x  # ❌ = operatoru işləməz

In [ ]:
# 4️⃣ Loops üçün tf.range istifadə et

@tf.function
def f(x):
    # for i in range(x):  # ❌ Python range - tracing-də işləyir
    for i in tf.range(x):  # ✅ tf.range - qrafikə düşür